name: Flypaper Python tests

on:
  pull_request_target:
    paths:
      - 'python/**'

defaults:
  run:
    working-directory: python

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Upgrade pip
        run: pip install -U pip
      - name: Install dev dependencies
        run: pip install -e .[dev]
      - name: Mypy type check
        run: mypy flypaper/
      - name: Black syntax check
        run: black --check flypaper/
      - name: Flypaper Python unit tests
        run: python -m unittest discover -v
